#!/usr/bin/env python3
"""Repository checks and progress report for embedded-linux-roadmap.

Commands (run from anywhere inside the repository):
  check              Validate internal links and anchors, topic reports, TRACKING.md
                     claims, daily logs and, if configured, a local private denylist.
                     Exits with status 1 when an error is found.
  progress [--write] Print the generated progress tables; --write updates the
                     marked blocks in README.md and leetcode/.
  history            List commits whose message, paths or added lines match the
                     private denylist.

Standard library only (Python 3.9+); works on Linux, macOS and Windows.
"""

from __future__ import annotations

import argparse
import datetime as dt
import functools
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent.parent
TODAY = dt.date.today()
DEFAULT_DENYLIST = Path.home() / ".config" / "embedded-linux-roadmap" / "denylist.txt"

TOPIC_PARENTS = ("c-cpp-foundation", "arm-architecture", "linux-system", "linux-kernel", "hardware")
TOPIC_EXCLUDE = ("hardware/boards",)
README_STATUS = ("Not started", "In progress", "Blocked", "Done")
REPORT_STATUS = ("Not run", "In progress", "Blocked", "Done")
LEVELS = ("L0", "L1", "L2", "L3", "L4")
GATES = ("Cổng 1", "Cổng 2", "Mở rộng", "Luyện tập", "Tùy chọn")
CORE_GATES = ("Cổng 1", "Cổng 2")
GATE_LABELS = {
    "Cổng 1": "Gate 1 core",
    "Cổng 2": "Gate 2 core (in addition to Gate 1)",
    "Mở rộng": "Extensions (after the core path is stable)",
    "Luyện tập": "Practice tracks (measured, not gating)",
    "Tùy chọn": "Optional",
}
REVERIFY_DAYS = 90
APPLIED_PREFIXES = ("projects/", "debug-logs/", "docs/", "sprints/")
LC_LEVELS = ("Easy", "Medium", "Hard")
LC_RESULTS = ("Not started", "Solved", "Solved có gợi ý", "Verified", "Chưa xong")
LC_DONE = ("Solved", "Solved có gợi ý", "Verified")

MARK_START, MARK_END = "<!-- progress:start -->", "<!-- progress:end -->"
GENERATED = re.compile(r"^_Generated by .*_$", re.M)
FENCE = re.compile(r"^```.*?^```[^\n]*$", re.M | re.S)
INLINE_CODE = re.compile(r"`[^`\n]*`")
LINK = re.compile(r"!?\[[^\]]*\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)")
HEADING = re.compile(r"^#{1,6}[ \t]+(.+?)[ \t]*#*[ \t]*$", re.M)
STATUS = re.compile(r"^Status:[ \t]*(.+?)[ \t]*$", re.M)
TRACK_ID = re.compile(r"^[A-Z]{2}\d{2}$")
LOG_ENTRY = re.compile(r"^(?:- )?(\d{4}-\d{2}-\d{2}) · [^·]+ · [^·]+ · .+$")


# --- helpers -------------------------------------------------------------------

def git(*args: str) -> str:
    result = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, check=True)
    return result.stdout.decode("utf-8", "replace")


@functools.lru_cache(maxsize=None)
def repo_files() -> tuple[Path, ...]:
    """Tracked plus untracked-but-not-ignored files that exist on disk."""
    listing = git("ls-files", "-z", "--cached", "--others", "--exclude-standard")
    return tuple(sorted({ROOT / p for p in listing.split("\0") if p and (ROOT / p).is_file()}))


def rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def drop_fences(text: str) -> str:
    """Blank fenced code blocks but keep line numbers stable."""
    return FENCE.sub(lambda m: "\n" * m.group(0).count("\n"), text)


def blank_code(text: str) -> str:
    return INLINE_CODE.sub("``", drop_fences(text))


def slugify(heading: str) -> str:
    """GitHub-style heading anchor."""
    text = re.sub(r"<[^>]+>", "", heading.strip().lower())
    text = re.sub(r"[^\w\- ]", "", text)
    return text.replace(" ", "-")


@functools.lru_cache(maxsize=None)
def anchors(path: Path) -> frozenset[str]:
    found: set[str] = set()
    counts: dict[str, int] = {}
    for heading in HEADING.findall(drop_fences(read(path))):
        base = slugify(heading)
        seen = counts.get(base, 0)
        found.add(base if seen == 0 else f"{base}-{seen}")
        counts[base] = seen + 1
    return frozenset(found)


def is_external(url: str) -> bool:
    return url.startswith("//") or bool(re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", url))


def exists_exact(path: Path) -> bool:
    """Case-sensitive existence inside the repository, as on GitHub and Linux.

    normpath, unlike resolve(), keeps the spelling of the link, so a wrong case is
    still caught on case-insensitive file systems.
    """
    absolute = Path(os.path.normpath(os.path.abspath(path)))
    try:
        parts = absolute.relative_to(ROOT).parts
    except ValueError:
        return absolute.exists()
    current = ROOT
    for part in parts:
        try:
            if part not in os.listdir(current):
                return False
        except OSError:
            return False
        current = current / part
    return True


@functools.lru_cache(maxsize=None)
def repo_paths() -> frozenset[str]:
    """Files and directories that will exist in a fresh clone (git-ignored paths excluded)."""
    paths: set[str] = set()
    for path in repo_files():
        parts = path.relative_to(ROOT).parts
        for end in range(1, len(parts) + 1):
            paths.add("/".join(parts[:end]))
    return frozenset(paths)


def in_repo(path: Path) -> bool:
    """True when the path is part of the repository, not just present on this disk."""
    absolute = Path(os.path.normpath(os.path.abspath(path)))
    try:
        relative = absolute.relative_to(ROOT).as_posix()
    except ValueError:
        return False
    return relative == "." or relative in repo_paths()


def link_targets(source: Path, text: str):
    """Yield (line, url, target, anchor) for every internal link in markdown text."""
    for match in LINK.finditer(text):
        url = match.group(1)
        if is_external(url):
            continue
        path_part, _, anchor = url.partition("#")
        target = source.parent / unquote(path_part) if path_part else source
        yield text.count("\n", 0, match.start()) + 1, url, target, unquote(anchor)


def split_row(line: str) -> list[str]:
    inner = line.strip()
    if inner.startswith("|"):
        inner = inner[1:]
    if inner.endswith("|") and not inner.endswith("\\|"):
        inner = inner[:-1]
    return [cell.strip() for cell in re.split(r"(?<!\\)\|", inner)]


def table_rows(block: str) -> list[list[str]]:
    """Rows of the markdown tables in block, separator rows removed."""
    rows = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and not set(stripped) <= set("|-: "):
            rows.append(split_row(stripped))
    return rows


def section(text: str, title: str) -> str:
    match = re.search(rf"^## {re.escape(title)}[ \t]*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    return match.group(1) if match else ""


def status_of(path: Path) -> str | None:
    match = STATUS.search(read(path))
    return match.group(1) if match else None


# --- topics and reports ----------------------------------------------------------

def topic_dirs() -> list[Path]:
    dirs = set()
    for path in repo_files():
        parts = path.relative_to(ROOT).parts
        if len(parts) >= 3 and parts[0] in TOPIC_PARENTS:
            folder = f"{parts[0]}/{parts[1]}"
            if folder not in TOPIC_EXCLUDE:
                dirs.add(ROOT / parts[0] / parts[1])
    return sorted(dirs)


def report_result(report: Path) -> tuple[bool, bool]:
    """(has a Pass/Fail row, has an existing evidence link) in the Results section."""
    block = section(read(report), "Results")
    executed = any(cell in ("Pass", "Fail") for row in table_rows(block)[1:] for cell in row)
    linked = any(exists_exact(t) and in_repo(t) for _, _, t, _ in link_targets(report, blank_code(block)))
    return executed, linked


def check_links(errors: list[str]) -> int:
    markdown = [p for p in repo_files() if p.suffix == ".md"]
    for md in markdown:
        for line, url, target, anchor in link_targets(md, blank_code(read(md))):
            if not exists_exact(target):
                errors.append(f"{rel(md)}:{line}: broken link '{url}'")
            elif not in_repo(target):
                errors.append(f"{rel(md)}:{line}: link target is ignored by git and will be missing from the repository: '{url}'")
            elif anchor and target.suffix == ".md" and anchor not in anchors(target.resolve()):
                errors.append(f"{rel(md)}:{line}: missing anchor '{url}'")
    return len(markdown)


def check_topics(errors: list[str]) -> None:
    for topic in topic_dirs():
        for name, allowed in (("README.md", README_STATUS), ("REPORT.md", REPORT_STATUS)):
            path = topic / name
            if not path.is_file():
                errors.append(f"{rel(topic)}: missing {name}")
                continue
            status = status_of(path)
            if status not in allowed:
                errors.append(f"{rel(path)}: Status '{status}' is not one of: {', '.join(allowed)}")
            elif name == "REPORT.md" and status == "Done" and not all(report_result(path)):
                errors.append(f"{rel(path)}: Status Done needs a Pass/Fail row and an existing evidence link under Results")


# --- TRACKING.md -----------------------------------------------------------------

@dataclass
class Topic:
    area: str
    ident: str
    name: str
    where: str
    planned: str
    gate: str
    level: str
    verified: str
    evidence: str
    line: int

    @property
    def rank(self) -> int:
        return LEVELS.index(self.level) if self.level in LEVELS else -1

    @property
    def overdue(self) -> bool:
        """Only gate-core topics can be overdue; extensions and practice have no deadline."""
        months = re.findall(r"(\d{2})/(\d{4})", self.planned)
        if not months or self.rank >= 2 or self.gate not in CORE_GATES:
            return False
        month, year = months[-1]
        return (TODAY.year, TODAY.month) > (int(year), int(month))


def tracking(errors: list[str]) -> list[Topic]:
    path = ROOT / "TRACKING.md"
    if not path.is_file():
        errors.append("TRACKING.md: missing")
        return []
    topics: list[Topic] = []
    area = ""
    for number, line in enumerate(read(path).splitlines(), 1):
        heading = re.match(r"^###[ \t]+(.+?)[ \t]*$", line)
        if heading:
            area = heading.group(1)
            continue
        if not line.startswith("|"):
            continue
        cells = split_row(line)
        if not TRACK_ID.match(cells[0]):
            continue
        if len(cells) != 9:
            errors.append(f"TRACKING.md:{number}: {cells[0]} has {len(cells)} columns, expected 9")
            continue
        topics.append(Topic(area, cells[0], cells[1], cells[3], cells[4], cells[5], cells[6], cells[7], cells[8], number))
    return topics


def check_tracking(errors: list[str], warnings: list[str]) -> list[Topic]:
    topics = tracking(errors)
    base = ROOT / "TRACKING.md"
    seen: set[str] = set()
    for topic in topics:
        where = f"TRACKING.md:{topic.line}: {topic.ident}"
        if topic.ident in seen:
            errors.append(f"{where} duplicate ID")
        seen.add(topic.ident)
        if topic.gate not in GATES:
            errors.append(f"{where} gate '{topic.gate}' is not one of: {', '.join(GATES)}")
        if topic.rank < 0:
            errors.append(f"{where} level '{topic.level}' is not one of L0–L4")
            continue
        verified = None
        if topic.verified not in ("—", "-", ""):
            try:
                verified = dt.date.fromisoformat(topic.verified)
            except ValueError:
                errors.append(f"{where} Verified must be YYYY-MM-DD or —")
            else:
                if verified > TODAY:
                    errors.append(f"{where} Verified date is in the future")
        evidence = [t for _, _, t, _ in link_targets(base, blank_code(topic.evidence)) if exists_exact(t) and in_repo(t)]
        if topic.rank >= 2:
            if not evidence:
                errors.append(f"{where} {topic.level} needs an existing evidence link")
            for target in evidence:
                if target.name == "REPORT.md" and not report_result(target)[0]:
                    errors.append(f"{where} {rel(target)} has no Pass/Fail result yet")
        if topic.rank >= 3 and verified is None:
            errors.append(f"{where} {topic.level} needs a Verified date")
        if topic.rank == 4 and not any(rel(t).startswith(APPLIED_PREFIXES) for t in evidence):
            errors.append(f"{where} L4 needs evidence under projects/, debug-logs/, docs/ or sprints/")
        if topic.overdue:
            warnings.append(f"{where} overdue: planned {topic.planned}, level {topic.level}")
        if topic.rank >= 3 and verified and (TODAY - verified).days > REVERIFY_DAYS:
            warnings.append(f"{where} re-verify due: last verified {verified}")
    listed = " ".join(topic.where for topic in topics)
    for folder in topic_dirs():
        if f"{rel(folder)}/" not in listed:
            warnings.append(f"TRACKING.md: no row links to {rel(folder)}/")
    return topics


# --- daily log -------------------------------------------------------------------

def check_logs(errors: list[str]) -> set[dt.date]:
    days: set[dt.date] = set()
    for path in sorted((ROOT / "log").glob("*.md")):
        month = re.fullmatch(r"(\d{4})-(\d{2})\.md", path.name)
        if not month:
            errors.append(f"{rel(path)}: file name must be YYYY-MM.md")
            continue
        text = read(path)
        start = text.find("## Entries")
        if start < 0:
            errors.append(f"{rel(path)}: missing '## Entries' section")
            continue
        first = text.count("\n", 0, start) + 1
        for offset, raw in enumerate(text[start:].splitlines()[1:], 1):
            line = raw.strip()
            if line.startswith("#"):
                break
            if not line or line.startswith("<!--"):
                continue
            entry = LOG_ENTRY.match(line)
            if not entry:
                errors.append(f"{rel(path)}:{first + offset}: expected 'YYYY-MM-DD · area · output · commit/link'")
                continue
            try:
                day = dt.date.fromisoformat(entry.group(1))
            except ValueError:
                errors.append(f"{rel(path)}:{first + offset}: invalid date {entry.group(1)}")
                continue
            if (day.year, day.month) != (int(month.group(1)), int(month.group(2))):
                errors.append(f"{rel(path)}:{first + offset}: {day} does not belong in {path.name}")
            days.add(day)
    return days


# --- LeetCode --------------------------------------------------------------------

@dataclass
class LcTopic:
    readme: Path
    name: str
    problems: list[tuple[str, str]]  # (difficulty, result)

    @property
    def done(self) -> list[tuple[str, str]]:
        return [p for p in self.problems if p[1] in LC_DONE]

    @property
    def status(self) -> str:
        if not self.done:
            return "Not started"
        return "Done" if len(self.done) == len(self.problems) else "In progress"


def leetcode(errors: list[str]) -> list[LcTopic]:
    topics = []
    for readme in sorted((ROOT / "leetcode").glob("[0-9][0-9]-*/README.md")):
        text = read(readme)
        title = re.search(r"^# (.+)$", text, re.M)
        problems = []
        for cells in table_rows(section(text, "Bài"))[1:]:
            if len(cells) != 9:
                errors.append(f"{rel(readme)}: problem row has {len(cells)} columns, expected 9")
                continue
            difficulty, result = cells[2], cells[6]
            if difficulty not in LC_LEVELS:
                errors.append(f"{rel(readme)}: level '{difficulty}' is not one of {', '.join(LC_LEVELS)}")
            if result not in LC_RESULTS:
                errors.append(f"{rel(readme)}: result '{result}' is not one of: {', '.join(LC_RESULTS)}")
            problems.append((difficulty, result))
        topics.append(LcTopic(readme, title.group(1).strip() if title else readme.parent.name, problems))
    return topics


# --- progress --------------------------------------------------------------------

def count_glob(folder: str, pattern: str) -> int:
    return len(list((ROOT / folder).glob(pattern)))


def metrics(lc_topics: list[LcTopic], days: set[dt.date]) -> list[tuple[str, str, str]]:
    solved = sum(len(t.done) for t in lc_topics)
    verified = sum(1 for t in lc_topics for _, result in t.done if result == "Verified")
    debug_index = ROOT / "debug-logs" / "README.md"
    debug = sum(1 for row in table_rows(read(debug_index))[1:] if row and row[-1] != "Template")
    drills_index = ROOT / "debug-drills" / "README.md"
    drill_rows = table_rows(read(drills_index))[1:] if drills_index.is_file() else []
    drills_done = sum(1 for row in drill_rows if row and row[-1] == "Done")
    self_check = ROOT / "docs" / "self-check.md"
    text = read(self_check) if self_check.is_file() else ""
    answered = len(re.findall(r"^\s*- \[[xX]\]", text, re.M))
    questions = len(re.findall(r"^\s*- \[[ xX]\]", text, re.M))
    return [
        ("Days with logged output", str(len(days)), "—"),
        ("Debug journal entries", str(debug), "30"),
        ("Debug drills completed", f"{drills_done} / {len(drill_rows)}", "12"),
        ("LeetCode solved / verified", f"{solved} / {verified}", "60 / 30"),
        ("ADRs", str(count_glob("docs/adr", "[0-9][0-9][0-9][0-9]-*.md")), "5"),
        ("English write-ups", str(count_glob("docs/writeups", "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_*.md")), "12"),
        ("Self-check questions answered", f"{answered} / {questions}", f"{questions} / {questions}"),
    ]


def count_row(items: list[Topic]) -> list[int]:
    return [len(items), sum(t.rank >= 2 for t in items), sum(t.rank >= 3 for t in items), sum(t.overdue for t in items)]


def render_readme(topics: list[Topic], lc_topics: list[LcTopic], days: set[dt.date]) -> str:
    lines = [
        f"_Generated by `python tools/repo_check.py progress --write` on {TODAY.isoformat()}._",
        "",
        "| Scope | Topics | ≥ L2 reproduced | ≥ L3 verified | Overdue |",
        "| --- | --- | --- | --- | --- |",
    ]
    for gate in GATES:
        row = count_row([t for t in topics if t.gate == gate])
        lines.append(f"| {GATE_LABELS[gate]} | " + " | ".join(map(str, row)) + " |")
    lines += ["", "| Area | Topics | ≥ L2 reproduced | ≥ L3 verified | Overdue |", "| --- | --- | --- | --- | --- |"]
    areas: dict[str, list[Topic]] = {}
    for topic in topics:
        areas.setdefault(topic.area, []).append(topic)
    for area, items in areas.items():
        lines.append(f"| {area} | " + " | ".join(map(str, count_row(items))) + " |")
    lines.append("| **Total** | " + " | ".join(f"**{n}**" for n in count_row(topics)) + " |")
    lines += ["", "| Metric | Current | Target 06/2027 |", "| --- | --- | --- |"]
    lines += [f"| {name} | {current} | {target} |" for name, current, target in metrics(lc_topics, days)]
    return "\n".join(lines)


def render_leetcode(lc_topics: list[LcTopic]) -> str:
    lines = [
        "| # | Chủ đề | Bài gợi ý | Đã làm | Verified | Easy | Medium | Hard | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    totals = [0] * 6
    for topic in lc_topics:
        done = topic.done
        counts = [len(topic.problems), len(done), sum(r == "Verified" for _, r in done)]
        counts += [sum(d == level for d, _ in done) for level in LC_LEVELS]
        totals = [a + b for a, b in zip(totals, counts)]
        folder = topic.readme.parent.name
        lines.append(f"| {folder[:2]} | [{topic.name}]({folder}/README.md) | " + " | ".join(map(str, counts)) + f" | {topic.status} |")
    lines.append("| | **Tổng** | " + " | ".join(f"**{n}**" for n in totals) + " | |")
    return "\n".join(lines)


def replace_block(text: str, body: str) -> str | None:
    start, end = text.find(MARK_START), text.find(MARK_END)
    if start < 0 or end < start:
        return None
    return text[: start + len(MARK_START)] + "\n\n" + body + "\n\n" + text[end:]


def generated_files(topics: list[Topic], lc_topics: list[LcTopic], days: set[dt.date]) -> dict[Path, str]:
    """New contents of every file that carries generated progress."""
    outputs: dict[Path, str] = {}
    for path, body in ((ROOT / "README.md", render_readme(topics, lc_topics, days)),
                       (ROOT / "leetcode" / "README.md", render_leetcode(lc_topics))):
        new = replace_block(read(path), body)
        if new is not None:
            outputs[path] = new
    for topic in lc_topics:
        line = f"Status: {topic.status} · Đã làm: {len(topic.done)}/{len(topic.problems)}"
        outputs[topic.readme] = STATUS.sub(line, read(topic.readme), count=1)
    return outputs


def stale(outputs: dict[Path, str]) -> list[Path]:
    return [path for path, new in outputs.items() if GENERATED.sub("", read(path)) != GENERATED.sub("", new)]


def collect(errors: list[str], warnings: list[str]):
    return check_tracking(errors, warnings), leetcode(errors), check_logs(errors)


# --- privacy ---------------------------------------------------------------------

def load_denylist(option: str | None) -> tuple[Path, list[re.Pattern[str]]]:
    path = Path(option or os.environ.get("REPO_DENYLIST") or DEFAULT_DENYLIST).expanduser()
    if not path.is_file():
        return path, []
    patterns = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            patterns.append(re.compile(line, re.IGNORECASE))
        except re.error as exc:
            raise SystemExit(f"{path}:{number}: invalid pattern: {exc}")
    return path, patterns


def check_privacy(patterns: list[re.Pattern[str]], errors: list[str]) -> None:
    for path in repo_files():
        name = rel(path)
        lines = [(0, name)]
        data = path.read_bytes()
        if b"\0" not in data[:8192]:
            lines += list(enumerate(data.decode("utf-8", "replace").splitlines(), 1))
        for number, line in lines:
            for pattern in patterns:
                found = pattern.search(line)
                if found:
                    location = name if number == 0 else f"{name}:{number}"
                    errors.append(f"{location}: private term '{found.group(0)}'")


# --- commands --------------------------------------------------------------------

def cmd_check(args: argparse.Namespace) -> int:
    errors: list[str] = []
    warnings: list[str] = []
    markdown = check_links(errors)
    check_topics(errors)
    topics, lc_topics, days = collect(errors, warnings)
    for path in (ROOT / "README.md", ROOT / "leetcode" / "README.md"):
        if MARK_START not in read(path) or MARK_END not in read(path):
            errors.append(f"{rel(path)}: missing progress markers")
    outdated = stale(generated_files(topics, lc_topics, days))
    if outdated:
        warnings.append("progress is out of date in " + ", ".join(rel(p) for p in outdated)
                        + " (run: python tools/repo_check.py progress --write)")
    _, patterns = load_denylist(args.denylist)
    if patterns:
        check_privacy(patterns, errors)
    for message in warnings:
        print(f"warning: {message}")
    for message in errors:
        print(f"error: {message}")
    privacy = f"{len(patterns)} private pattern(s)" if patterns else "no private denylist configured"
    print(f"checked {markdown} markdown files, {len(topics)} tracked topics, "
          f"{len(lc_topics)} LeetCode topics; {privacy}")
    print(f"{len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


def cmd_progress(args: argparse.Namespace) -> int:
    errors: list[str] = []
    topics, lc_topics, days = collect(errors, [])
    if errors:
        for message in errors:
            print(f"error: {message}")
        return 1
    if not args.write:
        print(render_readme(topics, lc_topics, days))
        print()
        print(render_leetcode(lc_topics))
        return 0
    outputs = generated_files(topics, lc_topics, days)
    changed = stale(outputs)
    for path in changed:
        write(path, outputs[path])
    print(f"updated {len(changed)} file(s)" + (": " + ", ".join(rel(p) for p in changed) if changed else ""))
    return 0


def cmd_history(args: argparse.Namespace) -> int:
    path, patterns = load_denylist(args.denylist)
    if not patterns:
        print(f"No denylist at {path}; nothing to scan.")
        return 0
    log = git("log", "--all", "-p", "--no-color", "--unified=0", "--format=@@@COMMIT %h %s%n%B")
    hits: dict[str, set[str]] = {}
    commit, current, in_diff = "", "", False
    for line in log.splitlines():
        if line.startswith("@@@COMMIT "):
            commit, current, in_diff = line[len("@@@COMMIT "):], "", False
            scope, text = "message", commit
        elif line.startswith("diff --git "):
            in_diff, current = True, line.rsplit(" b/", 1)[-1]
            scope, text = "path", current
        elif not in_diff:
            scope, text = "message", line
        elif line.startswith("+") and not line.startswith("+++"):
            scope, text = current, line[1:]
        else:
            continue
        for pattern in patterns:
            found = pattern.search(text)
            if found:
                hits.setdefault(commit, set()).add(f"{scope}: '{found.group(0)}'")
    for commit, places in hits.items():
        print(commit)
        for place in sorted(places):
            print(f"  {place}")
    print(f"{len(hits)} commit(s) contain private terms" if hits else "No private terms found in history.")
    return 1 if hits else 0


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--denylist", help="private denylist file (default: $REPO_DENYLIST or "
                                           "~/.config/embedded-linux-roadmap/denylist.txt)")
    parser = argparse.ArgumentParser(description="Repository checks and progress report.")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("check", parents=[common], help="validate the repository")
    progress = commands.add_parser("progress", help="print or update generated progress tables")
    progress.add_argument("--write", action="store_true", help="update the marked blocks in place")
    commands.add_parser("history", parents=[common], help="scan commit history for private terms")
    args = parser.parse_args()
    return {"check": cmd_check, "progress": cmd_progress, "history": cmd_history}[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
